-- Starwell HQ seed data — current site content. Run AFTER schema.sql.

insert into public.portfolio_companies (pillar,name,role,description,website_url,logo_url,partner,location,image_label,highlight,sort_order) values
('technology','Cormi IT','Founder and Majority Shareholder','Implementation and integration company specializing in ERP, CRM, and workflow systems for traditional businesses.','https://www.cormi.com/','https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/689dffc3f89591b3d4bd4a0b/fa2134825_Cormi-04.png',null,null,'Technology',false,1),
('technology','Doss Inc','Strategic Partner','Adaptive ERP and data platform with composable architecture. Unifies fragmented workflows across orders, inventory, procurement, production, and finance.','https://www.doss.com/','https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/689dffc3f89591b3d4bd4a0b/2f8d344a1_doss-black.jpg',null,null,'Technology',false,2),
('real-estate','Beyond Towers','Advisory & Owner Representative (Doron Kochavi)','Large-scale mixed-use development comprising office, residential, and commercial space. Total project value estimated at NIS 4–4.5 billion.',null,null,'Tidhar Group, Union Group, Himnuta–KKL','Tel Aviv, Israel','Tel Aviv',true,1),
('real-estate','Rova 7 — Mevoot Yafo','Strategic Advisory — municipality relations, commercial concept, and marketing strategy','55-dunam urban renewal project encompassing approximately 890 residential units, 5,000 sqm of commercial space, 20,000 sqm of office space, and 12 dunams of public area. Approved master plan (May 2023).',null,null,'Keren Reality, Kardan Real Estate (50/50 JV)','Tel Aviv, Israel','Urban Renewal',false,2),
('real-estate','The Dawson','Limited Partner','192-unit multifamily value-add acquisition.',null,'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/689dffc3f89591b3d4bd4a0b/37430c127_wilpon.png','Wilpon & Co.','Cartersville, Georgia, US','Multifamily',true,3),
('real-estate','Terminal Logistics Fund II','Limited Partner','Private real estate fund focused on industrial logistics assets across US markets.','https://www.terminallogistics.com/','https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/689dffc3f89591b3d4bd4a0b/e36794212_66e195f269802b9bae65b06b_Maskgroup10.png','Center Capital Partners','US Logistics Markets','Industrial Logistics',true,4),
('real-estate','Kochavi Real Estate Portfolio','Portfolio-level management, advisory, and future development planning','Multi-decade development and investment portfolio built by Doron Kochavi, encompassing over 750 units across more than 20 buildings in Tel Aviv.',null,null,'Developer: Doron Kochavi','Tel Aviv, Israel','Portfolio',false,5),
('capital','Pioneers — Healthcare Staffing AI Roll-Up','Investor','AI-native roll-up of healthcare staffing agencies, modernizing legacy operators with proprietary AI to automate workflows and dramatically improve recruiter output.','https://legionholdings.ai/','https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/689dffc3f89591b3d4bd4a0b/0a07f19ca_Screenshot2026-03-16at184317.png',null,null,'Capital',true,1),
('capital','Legion Holdings','Investor','AI-native growth buyout firm investing in business services companies, modernizing their operations with AI, and compounding value through disciplined M&A.','https://legionholdings.ai/','https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/689dffc3f89591b3d4bd4a0b/bb4d49516_LogoBluewithLegiononsidetransparentwithadditionalheightemailsig_1756064682174-C1uX8d2f.png',null,null,'Capital',true,2),
('capital','Noked Capital',null,'Hedge fund allocation.',null,'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/689dffc3f89591b3d4bd4a0b/40322a721_logofotter.png',null,null,'Capital',false,3),
('capital','Hazavim',null,'Hedge fund allocation.',null,'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/689dffc3f89591b3d4bd4a0b/7198da834_logo-black-new.png',null,null,'Capital',false,4);

insert into public.news_articles (category,publish_date,title,excerpt,source_url,featured_image_url,featured,sort_order) values
('Real Estate','2025-12-21','Lipa Meir to Rent Offices in Beyond Tower for 11 Million NIS Per Year','Lipa Meir & Co. is leaving Amot Investments House in Tel Aviv to lease 7,000 sqm of office space across 4 floors in the Beyond Tower project from Tidhar, Union, and Himnuta.','https://www.calcalist.co.il/real-estate/article/bjoi20k003','https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/689dffc3f89591b3d4bd4a0b/c758ca080_--beyond---2.jpg',true,0),
('Company News','2025-06-03','Circles Merges Operations with U.S.-Based Doss','Circles is merging its operations with U.S.-based Doss and will become the Israeli sales and marketing center for the company.',null,'https://www.new-techeurope.com/wp-content/uploads/2025/06/Amit-Kochavi-e1748940333350.jpg',false,1),
('Company News','2025-05-29','חברת Circles מתמזגת עם Doss האמריקאית','חברת Circles מתמזגת עם Doss האמריקאית ותהפוך למרכז הפיתוח הישראלי שלה. עמית כוכבי ימונה למנהל הפיתוח הגלובלי.',null,'https://www.ittime.co.il/wp-content/uploads/2025/05/Amit-Cohavi-200x300.jpeg',false,2),
('Real Estate','2025-05-06','Lee & Associates – Atlanta Facilitates Sale of 28-Acre Industrial Site to Terminal Logistics','Center Capital''s IOS platform, Terminal Logistics, has acquired a 28-acre site in Gainesville, GA.',null,'https://www.lee-associates.com/atlanta/wp-content/uploads/sites/77/2021/08/Lee-Associates-Atlanta-Logo-2021.png',false,3),
('Real Estate','2024-09-04','גבעתיים על הגובה: המגדל שהפך לגבוה בישראל','פרויקט ביונד בגבעתיים חצה את גובה 240 המטרים והפך למגדל הגבוה בישראל. בסיום הבנייה יגיע לגובה 320 מטרים.',null,'https://ynet-pic1.yit.co.il/cdn-cgi/image/f=auto,w=740,q=75/picserver5/crop_images/2024/09/04/SysC3IrnR/SysC3IrnR_0_0_1600_1067_0_x-large.jpg',false,4),
('Real Estate','2024-09-04','New Tower Claims Title of Tallest in Israel','New tower in Givataim claims title of tallest in Israel, rising to 320 meters with office and residential space.',null,'https://ynet-pic1.yit.co.il/cdn-cgi/image/format=auto/picserver5/crop_images/2024/09/03/S1v8iCV3A/S1v8iCV3A_0_113_460_820_0_x-large.jpg',false,5),
('Real Estate','2022-11-15','Meitar Leases 17 Floors in Givatayim Tower','Meitar Law Offices leases 17 floors in Givatayim tower for NIS 54 million annually.',null,'https://res.cloudinary.com/globes/image/upload/t_desktop_article_content_header_800%2A392/v1668451686/direct/x.jpg',false,6);
